### ISSUE TITLE
[Proposal] Addressing STDOUT for web/IIS containers

### ISSUE THREAD

**Issue by stephenpope** [Sitecore/docker-images#100]
It would be nice when working with the containers to see the output of : 1) IIS Logs + 2) Sitecore logs when doing things like `docker logs <containerid>` or `kubectl logs <podid>` or when running docker-compose .. all of which take data from STDOUT.

We all know that ServiceMonitor does not output to STDOUT and Microsoft are being very slow at add this (its Issue #1 on their list!). Currently the options are to write our own ServiceMonitor replacement (Not a fan of C++ :P) or find some other solution.

My proposal is to use FileBeats from Elastic (The OSS / Apache licensed version) and build this into the image to provide STDOUT output.
https://www.elastic.co/downloads/beats/filebeat-oss

It is very small and flexible it can take a series of inputs (iis logs + sitecore logs) and has different outputs .. one of them is console (STDOUT).

Example config :

``` yml
filebeat.modules:
- module: iis
  access:
    var.paths: ["C:/inetpub/logs/LogFiles/*/*.log"]
  error:
    var.paths: ["C:/Windows/System32/LogFiles/HTTPERR/*.log"]
output.console:
  codec.format:
    string: '%{[message]}'
```

https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-log.html

This would provide the STDOUT functionality we need plus, as a bonus, this would also allow people to very easily configure the container to ship their logs to things like logstatsh/kafka/redis and other places.

https://www.elastic.co/guide/en/beats/filebeat/current/configuring-output.html

The change would require a "boot script" of sorts to enable filebeat to 'own' the STDOUT :

``` powershell
Start-Job -Name ServiceMonitor {    
	C:\ServiceMonitor.exe W3SVC
	ps filebeat | kill -Force
}

C:\filebeat\filebeat.exe -c C:\filebeat\filebeat.yml
```

We know that ServiceMonitor checks the w3wp process and if it is stopped or it crashes then the process quits (and so stops the container). This tiny bootscript would still cover the same behaviour, if ServiceMonitor quits then filebeat is killed and the process will exit as planned.

Just an idea anyway .. interested to know what people think about this solution as i think we need to offer a proper STDOUT solution for people using the containers.
